imu_rt:
  ros__parameters:
    frame_id: "imu"
    port: "/dev/ttyACM0"
    linear_acceleration_stddev: 20.0
    angular_velocity_stddev: 0.1
    # magnetic_field_stddev: 0.00000080786

imu_filter:
  ros__parameters:
    use_mag: true
    publish_tf: false
    reverse_tf: false
    world_frame: "ned"
    fixed_frame: "imu"
    orientation_stddev: 1.0
    mag_bias_x:  0.000011
    mag_bias_y:  0.000003
    mag_bias_z: -0.0000385
    yaw_offset: 1.7
    gain: 0.7