scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: robot_body_outline
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: laser
        max_x: 0.26
        max_y: 0.33
        max_z: 0.35
        min_x: -0.26
        min_y: -0.33
        min_z: -0.25
        invert: false    
    filter2:
      name: al_frame_front_right
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        angle_max: 2.36
        angle_min: 2.10
    filter3:
      name: al_frame_rear_right
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        angle_max: 1.06
        angle_min: 0.84
    filter4:
      name: al_frame_rear_left
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        angle_min: -1.06
        angle_max: -0.84
    filter5:
      name: al_frame_front_left
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        angle_min: -2.36
        angle_max: -2.10
