scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: robot_body_outline
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: laser
        max_x: 0.26
        max_y: 0.33
        max_z: 0.35
        min_x: -0.26
        min_y: -0.33
        min_z: -0.25
        invert: false
    filter2:
      name: al_frame_front_right
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle: 2.10
        upper_angle: 2.36
    filter3:
      name: al_frame_rear_right
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle: 0.84
        upper_angle: 1.06
    filter4:
      name: al_frame_rear_left
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle: -1.06
        upper_angle: -0.79
    filter5:
      name: al_frame_front_left
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle: -2.36
        upper_angle: -2.00