navsat_transform:
  ros__parameters:
    use_sim_time: false
    frequency: 2.0
    delay: 1.0
    magnetic_declination_radians: -0.137
    yaw_offset: 1.57
    zero_altitude: true
    broadcast_utm_transform: true
    broadcast_utm_transform_as_parent_frame: true
    publish_filtered_gps: true
    use_odometry_yaw: false
    wait_for_datum: false
